spring:
  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
    driver-class-name: ${db_driver}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug