spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1085354012339-cmrj7uofqlc2an285ntc97i03sfragh1.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: eih63lIz2FFmWgYcV6Ch
            client-secret: hZSg09oUAh
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: fef18571b5f45c6a318be7b9042c4997
            client-secret: BmfPnjWvKOVu00ipW7MTYM13vjPwRXIG
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id