on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'cicd'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: create application yaml
        run: |
          touch ./src/main/resources/application.yml
          echo "${{secrets.APPLICATION}}" > ./src/main/resources/application.yml


      - uses: actions/upload-artifact@v3
        with:
          name: application.yml
          path: ./src/main/resources/application.yml


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Build with Gradle
        run: ./gradlew build


      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_REPO }}/cicd:latest
          docker push ${{ secrets.DOCKER_REPO }}/cicd:latest


      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/cicd:latest
            docker stop $(docker ps -a -q)
            docker run -d --log-driver=syslog -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/cicd:latest
            docker rm $(docker ps --filter 'status=exited' -a -q)
            docker image prune -a -f
