on:
  push:
    branches:
      - 'main'
      - 'cicd'
  pull_request:
    branches:
      - "main"


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'


      - name: create application yaml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{secrets.APPLICATION}}" > ./application.yml


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - uses: actions/upload-artifact@v3
        with:
          name: application.yml
          path: ./src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew build


      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/cicd:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd:latest


      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/cicd:latest
            docker stop Backend
            docker rm Backend && docker rmi ${{ secrets.DOCKER_USERNAME }}/cicd:latest
            docker run -d -p 8080:8080 --name Backend --restart always ${{ secrets.DOCKER_USERNAME }}/cicd:latest
#            docker image prune -a -f
